<Project>
  <ItemGroup>
    <GlobalPackageReference Include="MartinCostello.BuildKit" Version="0.8.5" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.23.4" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.4-alpha.0.159" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.15.3-beta.1.157" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.4-alpha.0.159" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.3-alpha.0.213" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AWS" Version="1.15.2-alpha.0.214" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.2-alpha.0.201" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.15.3-alpha.0.195" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.15.1-beta.1.194" />
    <PackageVersion Include="StackExchange.Redis" Version="2.13.10" />
    <PackageVersion Include="Testcontainers" Version="4.12.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.12.0" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.12.0" />
  </ItemGroup>
</Project>
