<Project>
  <ItemGroup>
    <GlobalPackageReference Include="MartinCostello.BuildKit" Version="0.8.11" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.102" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.1-alpha.0.67" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.17.0-beta.1.65" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.17.1-alpha.0.67" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.1-alpha.0.128" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AWS" Version="1.17.1-alpha.0.83" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.17.0-beta.1.115" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.17.1-alpha.0.127" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.17.1-alpha.0.117" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.17.0-beta.1.122" />
    <PackageVersion Include="StackExchange.Redis" Version="3.1.13" />
    <PackageVersion Include="Testcontainers" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.13.0" />
  </ItemGroup>
</Project>
