<Project>
  <ItemGroup>
    <GlobalPackageReference Include="MartinCostello.BuildKit" Version="0.8.13" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.103.3" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.1-alpha.0.75" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.18.0-beta.1.73" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.1-alpha.0.75" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.1-alpha.0.128" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AWS" Version="1.18.1-alpha.0.130" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.18.0-beta.1.117" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.1-alpha.0.122" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.18.1-alpha.0.103" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.18.0-beta.3" />
    <PackageVersion Include="StackExchange.Redis" Version="3.2.1" />
    <PackageVersion Include="Testcontainers" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.15.0" />
  </ItemGroup>
</Project>