<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Benchmarks for ASP.NET Core and OpenTelemetry.</Description>
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
    <OutputType>Exe</OutputType>
    <PublishAot>false</PublishAot>
    <RootNamespace>MartinCostello.AspNetCoreOpenTelemetry.Benchmarks</RootNamespace>
    <TargetFrameworks>net11.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="*.Dockerfile" LogicalName="%(FileName)%(Extension)" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AWS" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
  </ItemGroup>
  <ItemGroup>
    <!-- See https://learn.microsoft.com/aspnet/core/release-notes/aspnetcore-11#native-opentelemetry-tracing-for-aspnet-core -->
    <RuntimeHostConfigurationOption Include="Microsoft.AspNetCore.Hosting.SuppressActivityOpenTelemetryData" Value="true" />
  </ItemGroup>
</Project>
